services:
  postgres:
    image: postgres
    container_name: my-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=supersecret123
      - POSTGRES_DB=minitwitter
    volumes:
      - ./docker-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minitwitter-1:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:supersecret123@postgres:5432/minitwitter
    depends_on:
      postgres:
        condition: service_healthy

  minitwitter-2:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:supersecret123@postgres:5432/minitwitter
    depends_on:
      postgres:
        condition: service_healthy

  load-balancer:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - minitwitter-1
      - minitwitter-2

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
    - "11434:11434"
    volumes:
    - ./docker-data/ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24
