worker_processes 1;

events {
  worker_connections 1024;
}

http {

  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  types { image/svg+xml svg; }

  upstream backend {
    server minitwitter-1:3000;
    server minitwitter-2:3000;
  }

  server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Frontend
    location / {
      try_files $uri $uri/ /index.html;
    }

    # Backend API
    location /auth {
      proxy_pass http://backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /posts {
      proxy_pass http://backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
